=== nido/vegastrike-market/data/economy.dtd
<!ELEMENT ProductionOption (Cargo, Cargo)>
<!ATTLIST ProductionOption>

<!ELEMENT Cargo (CargoType+)>
<!ATTLIST Cargo
	type (in|out) #IMPLIED
>

<!ELEMENT vector ((CargoType|Cargo|ProductionOption)+)>
<!ATTLIST vector
	type CDATA #REQUIRED
>
<!ELEMENT CargoType (#PCDATA)>
<!ATTLIST CargoType
	name CDATA #REQUIRED
	category CDATA #REQUIRED
	mass CDATA #REQUIRED
	volume CDATA #REQUIRED
	price CDATA #REQUIRED
>

=== nido/vegastrike-market/data/ProductionOption.xml
<?xml version="1.0"?>
<!DOCTYPE vector_cargo SYSTEM "economy.dtd">
<vector type="ProductionOption">
<ProductionOption><Cargo type="in"><CargoType category="categoryname" mass="0" name="file" price="0" volume="0">1</CargoType></Cargo><Cargo type="out"><CargoType category="categoryname" mass="0" name="file" price="0" volume="0">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Heavy" mass="275" name="Admonisher.stock" price="3e+06" volume="5600">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Heavy" mass="275" name="Admonisher.stock" price="3e+06" volume="5600">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Homeland-Security/Milspec" mass="275" name="Admonisher.HSspec" price="3e+06" volume="5600">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Homeland-Security/Milspec" mass="275" name="Admonisher.HSspec" price="3e+06" volume="5600">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Milspec" mass="275" name="Admonisher.milspec" price="3.5e+06" volume="5600">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Milspec" mass="275" name="Admonisher.milspec" price="3.5e+06" volume="5600">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="upgrades/Packages/Milspec" mass="275" name="Admonisher_Milspec_Package" price="2.5e+06" volume="5600">1</CargoType></Cargo><Cargo type="out"><CargoType category="upgrades/Packages/Milspec" mass="275" name="Admonisher_Milspec_Package" price="2.5e+06" volume="5600">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Purist/Milspec" mass="275" name="Admonisher.puristspec" price="3e+06" volume="5600">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Purist/Milspec" mass="275" name="Admonisher.puristspec" price="3e+06" volume="5600">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Regional_Guard/Heavy" mass="275" name="Admonisher.rgspec" price="3e+06" volume="5600">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Regional_Guard/Heavy" mass="275" name="Admonisher.rgspec" price="3e+06" volume="5600">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Pirate/Heavy" mass="275" name="Admonisher.salvage" price="2e+06" volume="5600">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Pirate/Heavy" mass="275" name="Admonisher.salvage" price="2e+06" volume="5600">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Shaper/Light" mass="40" name="Ancestor.stock" price="190000" volume="1000">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Shaper/Light" mass="40" name="Ancestor.stock" price="190000" volume="1000">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Milspec" mass="40" name="Ancestor.milspec" price="700000" volume="800">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Milspec" mass="40" name="Ancestor.milspec" price="700000" volume="800">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="upgrades/Packages/Milspec" mass="40" name="Ancestor_Milspec_Package" price="500000" volume="800">1</CargoType></Cargo><Cargo type="out"><CargoType category="upgrades/Packages/Milspec" mass="40" name="Ancestor_Milspec_Package" price="500000" volume="800">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Shaper/Milspec" mass="40" name="Ancestor.shaperspec" price="525000" volume="800">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Shaper/Milspec" mass="40" name="Ancestor.shaperspec" price="525000" volume="800">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Aera/Milspec" mass="216" name="Areus.milspec" price="6e+06" volume="4400">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Aera/Milspec" mass="216" name="Areus.milspec" price="6e+06" volume="4400">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="upgrades/Packages/Milspec" mass="216" name="Areus_Milspec_Package" price="4e+06" volume="4400">1</CargoType></Cargo><Cargo type="out"><CargoType category="upgrades/Packages/Milspec" mass="216" name="Areus_Milspec_Package" price="4e+06" volume="4400">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Aera/Heavy" mass="197" name="Ariston.stock" price="2.7e+06" volume="4000">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Aera/Heavy" mass="197" name="Ariston.stock" price="2.7e+06" volume="4000">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Aera/Milspec" mass="197" name="Ariston.milspec" price="3.5e+06" volume="4000">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Aera/Milspec" mass="197" name="Ariston.milspec" price="3.5e+06" volume="4000">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="upgrades/Packages/Milspec" mass="197" name="Ariston_Milspec_Package" price="2.5e+06" volume="4000">1</CargoType></Cargo><Cargo type="out"><CargoType category="upgrades/Packages/Milspec" mass="197" name="Ariston_Milspec_Package" price="2.5e+06" volume="4000">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Light_Capship" mass="2.9e+07" name="Clydesdale.milspec" price="4e+08" volume="5.9e+08">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Light_Capship" mass="2.9e+07" name="Clydesdale.milspec" price="4e+08" volume="5.9e+08">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="upgrades/Packages/Milspec" mass="2.9e+07" name="Clydesdale_Milspec_Package" price="2e+08" volume="5.9e+08">1</CargoType></Cargo><Cargo type="out"><CargoType category="upgrades/Packages/Milspec" mass="2.9e+07" name="Clydesdale_Milspec_Package" price="2e+08" volume="5.9e+08">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Merchant/Light_Capship" mass="2.9e+07" name="Clydesdale.merchant" price="3e+08" volume="5.9e+08">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Merchant/Light_Capship" mass="2.9e+07" name="Clydesdale.merchant" price="3e+08" volume="5.9e+08">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Medium" mass="62" name="Convolution.stock" price="760000" volume="1280">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Medium" mass="62" name="Convolution.stock" price="760000" volume="1280">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Milspec" mass="62" name="Convolution.milspec" price="1.5e+06" volume="1280">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Milspec" mass="62" name="Convolution.milspec" price="1.5e+06" volume="1280">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="upgrades/Packages/Milspec" mass="62" name="Convolution_Milspec_Package" price="1e+06" volume="1280">1</CargoType></Cargo><Cargo type="out"><CargoType category="upgrades/Packages/Milspec" mass="62" name="Convolution_Milspec_Package" price="1e+06" volume="1280">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Medium" mass="134" name="Derivative.stock" price="800000" volume="2700">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Medium" mass="134" name="Derivative.stock" price="800000" volume="2700">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Milspec" mass="134" name="Derivative.milspec" price="1.2e+06" volume="2700">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Milspec" mass="134" name="Derivative.milspec" price="1.2e+06" volume="2700">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="upgrades/Packages/Milspec" mass="134" name="Derivative_Milspec_Package" price="800000" volume="2700">1</CargoType></Cargo><Cargo type="out"><CargoType category="upgrades/Packages/Milspec" mass="134" name="Derivative_Milspec_Package" price="800000" volume="2700">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Medium" mass="54" name="Determinant.stock" price="700000" volume="1100">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Medium" mass="54" name="Determinant.stock" price="700000" volume="1100">2</CargoType></Cargo></ProductionOption>
<ProductionOption><Cargo type="in"><CargoType category="starships/Confed/Milspec" mass="54" name="Determinant.milspec" price="1.2e+06" volume="1100">1</CargoType></Cargo><Cargo type="out"><CargoType category="starships/Confed/Milspec" mass="54" name="Determinant.milspec" price="1.2e+06" volume="1100">2</CargoType></Cargo></ProductionOption>
